#!/bin/python

import sys
import socket
from datetime import datetime

#Define The Target
if len(sys.argv) == 2:
	target == socket.gethostbyname(sys.argv[1]) #Translates hostname to IPV4
else:
	print("Invalid # of arguments")
	print("Syntax: python3 <filename> <ip>")
	
#Banner Creation
print("-" * 50)
print("Scanning Target "+target)
print("Time started: "+str(datetime.now()))
print("-" * 50)

try:
	for prot in range(50,85)
		s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
		socket.setdefaulttimeout(1)
		result = s.connect_ex((target,port)) #return the indicated error
		if result == 0:
			print("Port {} is open".format(port))
			s.close()

except KeyboardInterrupt:
	print("\nExiting program.")
	sys.exit()
	
except socket.gaierror:
	print("Hostname could not be resolved.")
	sys.exit()
	
except socket.error:
	print("Could not connect to server")
	sys.exit()
	
